project:
  type: website
  output-dir: docs

website:
  title: "Seedcorn maggot complex abundance in Québec, Canada"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

